DROP TABLE ORDER_DETAILS;
/
DROP TABLE BROKEN_PRODUCT;
/
DROP TABLE PRODUCT;
/
DROP TABLE CONTRACT;
/
DROP TABLE SUPPLY_DETAILS;
/
DROP TABLE SUPPLY;
/
DROP TABLE ABSTRACT_SUPPLY;
/
DROP TABLE APPLICATION_DETAILS;
/
DROP TABLE CUSTOMER_APPLICATION;
/
DROP TABLE CUSTOMER_ORDER;
/
DROP TABLE CUSTOMER;
/
DROP TABLE CELL;
/
DROP TABLE SPARE_PART;
/
DROP TABLE MANUFACTURER;
/
DROP TABLE FIRM;
/
DROP TABLE LITTLE_FACTORY;
/
DROP TABLE ABSTRACT_PROVIDER_ADAPTER;
/
DROP TABLE DEALER;
/
DROP TABLE SHOP;
/
DROP TABLE LITTLE_DEALER;
/
DROP TABLE PROVIDER;
/
DROP TABLE ABSTRACT_PROVIDER;
/
DROP TABLE COUNTRY;
/
DROP SEQUENCE SQ_ORDER_DETAILS;
/
DROP SEQUENCE SQ_BROKEN_PRODUCT;
/
DROP SEQUENCE SQ_PRODUCT;
/
DROP SEQUENCE SQ_CONTRACT;

DROP SEQUENCE SQ_SUPPLY;
/
DROP SEQUENCE SQ_ABSTRACT_SUPPLY;
/
DROP SEQUENCE SQ_APPLICATION_DETAILS;
/
DROP SEQUENCE SQ_CUSTOMER_APPLICATION;
/
DROP SEQUENCE SQ_CUSTOMER_ORDER;
/
DROP SEQUENCE SQ_CUSTOMER;
/
DROP SEQUENCE SQ_CELL;
/
DROP SEQUENCE SQ_SPARE_PART;
/
DROP SEQUENCE SQ_MANUFACTURER;
/
DROP SEQUENCE SQ_PROVIDER;
/
DROP SEQUENCE SQ_ABSTRACT_PROVIDER;
/
DROP SEQUENCE SQ_COUNTRY;